name: CICD-workshop-actions

on:
  push:
    branches:
    - 'releases/v[0-9]+.[0-9]+'

jobs:
  Scan:
    if: "!startsWith(github.event.head_commit.message, '#NORUN')"
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'table'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'HIGH'
          output: trivy.txt

      - name: Find trivytxt
        id: search_file
        run: |
          if grep -q "HIGH" trivy.txt; then
            echo "::set-output name=Trivy_Status::Failed"
          else
            echo "::set-output name=Trivy_Status::Success"
          fi
     

      - name: trivy failure send slack
        if: success() && steps.search_file.outputs.Trivy_Status == 'Failed'
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_TITLE: 'Scan failed - Sun Jiahao'
          SLACK_MESSAGE: 'Failed trivy scan, see uploaded report'
          SLACK_COLOR: 'failure'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}  


      - name: Upload Failure txt
        if: success() && steps.search_file.outputs.Trivy_Status == 'Failed'
        uses: MeilCli/slack-upload-file@v4
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
          file_path: 'trivy.txt'
          initial_comment: 'Scan report by Sun Jiahao.'

      - name: Install Cosign
        if: success() && steps.search_file.outputs.Trivy_Status == 'Success'
        uses: sigstore/cosign-installer@v3.5.0

      - name: Set up QEMU
        if: success() && steps.search_file.outputs.Trivy_Status == 'Success'
        uses: docker/setup-qemu-action@v2.1.0

      - name: Set up Docker Buildx
        if: success() && steps.search_file.outputs.Trivy_Status == 'Success'
        uses: docker/setup-buildx-action@v2.5.0

      - name: Login Docker 
        if: success() && steps.search_file.outputs.Trivy_Status == 'Success'
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - id: docker_meta
        if: success() && steps.search_file.outputs.Trivy_Status == 'Success'
        uses: docker/metadata-action@v4.4.0
        with:
          images: ghcr.io/sigstore/sample-honk
          tags: type=sha,format=long

      - name: Build and Push container images
        if: success() && steps.search_file.outputs.Trivy_Status == 'Success'
        uses: docker/build-push-action@v4.0.0
        id: build-and-push
        with:
          push: true
          tags: sun1ny/sun1nyworkshop:${{ github.sha }}

      - name: Sign image with a key
        if: success() && steps.search_file.outputs.Trivy_Status == 'Success'
        run: |
          images=""
          for tag in ${TAGS}; do
            images+="${tag}@${DIGEST} "
          done
          cosign sign --yes --key env://COSIGN_PRIVATE_KEY ${images}
        env:
          TAGS: sun1ny/sun1nyworkshop:${{ github.sha }}
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
      
      - name: trivy success send slack
        if: success() && steps.search_file.outputs.Trivy_Status == 'Success'
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_TITLE: 'Image build and signed'
          SLACKIFY_MARKDOWN: 'true'
          SLACK_MESSAGE: 
            '**Name**: Sun Jiahao \n
            **Metriculation**: A0291826W \n
            **Email**: [e1335038@u.nus.edu](e1335038@u.nus.edu) \n
            **Git**: ${{ github.server_url }}/${{ github.repository }} \n
            **Image**: https://hub.docker.com/repository/docker/sun1ny/sun1nyworkshop/general'
          SLACK_COLOR: 'success'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      
      
      
      # - name: Build and Push Docker Image
      #   if: success() && steps.search_file.outputs.Trivy_Status == 'Success'
      #   env:
      #     DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      #     DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      #   run: |
      #     echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      #     docker build -t sun1ny/sun1nyworkshop:${{ github.sha }} .
      #     docker push sun1ny/sun1nyworkshop:${{ github.sha }}


      # - name: Install Cosign
      #   uses: sigstore/cosign-installer@v2.1.0

      # - id: docker_meta
      #   uses: docker/metadata-action@v4.4.0
      #   with:
      #     images: sun1ny/sun1nyworkshop
      #     tags: |
      #       type=sha

      # - name: Sign image with a key
      #   if: success() && steps.search_file.outputs.Trivy_Status == 'Success'
      #   run: |
      #     images=""
      #     for tag in ${TAGS}; do
      #       images+="${tag}@${DIGEST} "
      #     done
      #     cosign sign --yes --key env://COSIGN_PRIVATE_KEY ${images}
      #   env:
      #     TAGS: sun1ny/sun1nyworkshop:${{ github.sha }}
      #     COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
      #     COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
      #     DIGEST: ${{ steps.build-and-push.outputs.digest }}

