name: CICD-workshop-actions
on:
  push:
    branches:
    - main
    tags:
    - 'releases/v[0-9]+.[0-9]+'
jobs:
  Scan:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Trivy vulnerability scanner in fs mode
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        format: 'table'
        ignore-unfixed: ture
        vuln-type: 'os-library'
        severity: 'CRITICAL'
        trivy-config: trivy.yaml
        output: trivy.txt
    Upload:
      runs-on: ubuntu-20.04
      steps:
      - name: Upload scan results
        uses: actions/upload-artifact@v3
        with:
          name: trivy-scan-results
          path: trivy.txt
  Send:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_COLOR: ${{ job.status }}
        SLACK_MESSAGE: '法法法'
  post:
    runs-on: ubuntu-latest
    needs: Scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download scan results
        uses: actions/download-artifact@v3
        with:
          name: trivy-scan-results

      - name: Upload scan results to Slack 
        uses: MeilCli/slack-upload-file@v4
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
          file_path: trivy.txt
          initial_comment: 'post by Sun Jiahao'
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: user/app:latest
  