name: CICD-workshop-actions

on:
  push:
    branches:
      - main
    tags:
      - 'releases/v[0-9]+.[0-9]+'

jobs:
  Scan:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'table'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'HIGH'
          output: trivy.txt

      - name: Find trivytxt
        id: search_file
        run: |
          if grep -q "HIGH" trivy.txt; then
            echo "::set-output name=Trivy_Status::Failed"
          else
            echo "::set-output name=Trivy_Status::Success"
          fi
     

      - name: Slack Notification When trivy failure
        if: success() && steps.search_file.outputs.Trivy_Status == 'Failed'
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_TITLE: 'Scan failed - Sun Jiahao'
          SLACK_MESSAGE: 'Failed trivy scan, see uploaded report'
          SLACK_COLOR: 'failure'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}  


      - name: Upload Failure txt
        if: success() && steps.search_file.outputs.Trivy_Status == 'Failed'
        uses: MeilCli/slack-upload-file@v4
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
          file_path: 'trivy.txt'
          initial_comment: 'Scan report by Sun Jiahao.'

