name: CICD-workshop-actions
on:
  push:
    branches:
    - main
    tags:
    - 'releases/v[0-9]+.[0-9]+'
jobs:
  Scan:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Trivy vulnerability scanner in fs mode
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        trivy-config: trivy.yaml
  Send:
    runs-on: ubuntu-20.04
    steps:
    - name: Send custom JSON data to Slack workflow
    id: slack
    uses: slackapi/slack-github-action@v1.26.0
    with:
    
    payload: |
        {
          "blocks": [
            {
              "type": "context",
              "elements": [
                {
                  "type": "image",
                  "image_url": "https://img2.baidu.com/it/u=3183561743,1887230437&fm=253&app=138&size=w931&n=0&f=JPEG&fmt=auto?sec=1715274000&t=2c7a77e6c4b8da90a2ba9f3b2f1a82d6",
                  "alt_text": "Sun Jiahao"
                },
                {
                  "type": "mrkdwn",
                  "text": "*Sun Jiahao*"
                }
              ]
            },
            {
              "type": "section",
              "fields": [
                {
                  "type": "mrkdwn",
                  "text": "*Re:*\nComputer (laptop)"
                },
                {
                  "type": "mrkdwn",
                  "text": "*Event:*\nSubmitted Aut 10"
                },
                {
                  "type": "mrkdwn",
                  "text": "*Actions URL:*\n*<fakeLink.toEmployeeProfile.com|Build and Push>*"
                },
                {
                  "type": "mrkdwn",
                  "text": "*Commit:*\n<fakeLink.toEmployeeProfile.com|CommitNo>"
                }
              ]
            },
            {
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": "*Scan failed - Sun Jiahao*\nFailed trivy scan, see uploaded report"
              }
            }
          ]
        }
    env:
      SLACK_WEBHOOK_URL: ${{ https://app.slack.com/client/T06U5JGHA5B/C06UB2DHPC4 }}